import {StyleSheet} from "react-native";
import {Colors} from "../utils/colors";

export const styles = StyleSheet.create({
    row: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: "5%",
    },
    item: {
        height: 50,
        width: "33%",
        backgroundColor: Colors.bluetitle,
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 5,
        // paddingHorizontal: "2%",
    },
    image: {
        width: 40,
        height: 40,
        resizeMode: "contain",
    },
    title: {
        fontFamily: "Cabin-Regular",
        fontSize: 12,
        color: Colors.white,
        textAlign: "center",
    },
    container: {
        width: "100%",
        minHeight: 350,
        backgroundColor: Colors.white,
        paddingHorizontal: 30,
        borderRadius: 30,
        marginBottom: 30,
        marginTop:25
    },
    input: {
        fontFamily: "Cabin-Regular",
        fontSize: 16,
        color: Colors.secondary,
        width: "100%",
        borderColor: Colors.primary,
        // borderWidth: 1,
        backgroundColor: Colors.back,
        marginBottom: 20,
        padding: 15,
        borderRadius: 10,
        textAlign: "center",
    },
    inputJustify: {
        fontFamily: "Cabin-Regular",
        fontSize: 16,
        color: Colors.bluetitle,
        width: "100%",
        borderColor: Colors.primary,
        // borderWidth: 1,
        backgroundColor: Colors.bluebg,
        marginBottom: 20,
        padding: 0,
        borderRadius: 10,
        textAlign: "justify",
    },
    inputComment: {
        fontFamily: "Cabin-Regular",
        fontSize: 16,
        color: Colors.bluetitle,
        width: "100%",
        height: 100,
        borderColor: Colors.primary,
        borderWidth: 1,
        marginBottom: 20,
        padding: 15,
        borderRadius: 10,
        backgroundColor: Colors.bluebg,
    },
});